pull_request_rules:
  - name: automatic merge on CI success require review
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - label=merge-when-green
      - label!=block-merge
    actions:
      merge:
        method: squash
        strict: smart

  - name: automatic merge on CI success for TemplateControl
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - label=merge-when-green
      - label=template-control
      - label!=block-merge
    actions:
      merge:
        method: squash
        strict: smart

  # delete any branch when already merged
  # doesn't matter if marked with labels or not
  - name: delete branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}

  # delete 'merge-when-green' label if present and merged
  - name: remove label after merge
    conditions:
      - merged
      - label=merge-when-green
    actions:
      label:
        remove: [merge-when-green]

  # delete 'template-control' label if present and merged
  - name: remove label after merge
    conditions:
      - merged
      - label=template-control
    actions:
      label:
        remove: [template-control]

  - name: auto add wip
    conditions:
      # match a few flavours of wip
      - title~=^(\[wip\]( |:) |\[WIP\]( |:) |wip( |:) |WIP( |:)).*
    actions:
      label:
        add: ["block-merge"]